### ISSUE TITLE
Sidebar floating div height on user profiles

### ISSUE THREAD

**Issue by thetmk** [mifune/gazelle#10]
http://xxx.freeimage.us/image.php?id=878D_51F597B4&jpg
http://xxx.freeimage.us/image.php?id=F3C4_51F597B4&jpg

The sidebar height is not taken into account, as it's a floating div. So we either need to add overflow:hidden; for #content or add another div at the end of the parent div that utilizes clear:both

**Comment by mifune** [comment]
yeah I have to confess this problem did not exist in gazelle originally... I introduced it at some point by removing the overflow:hidden from the div#content css class  (because.... there was a good reason, iirc its for some dropdown that was clipped by the content div). 

my preferred solution is adding <div class="clear"></div> to the html (which is a css class with  clear:both), its inelegant but allows the dropdown (wherever it is) to still work as desired. 

thanks for the heads up :)
